<a href="https://colab.research.google.com/github/iJianHuang/GenAI/blob/main/Bag_of_Words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Spam

#### Load CSV

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

df = pd.read_csv('/content/spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df.Category.value_counts() / len(df) * 100


Category
ham     86.593683
spam    13.406317
Name: count, dtype: float64

#### Add column 'spam'

In [6]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
df.shape

(5572, 3)

#### Train test split

In [9]:
# from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.25)

In [10]:
x_train.shape

(4179,)

In [11]:
x_test

2856    Your gonna be the death if me. I'm gonna leave...
1600      Yeah probably, I still gotta check out with leo
3873    I am joining today formally.Pls keep praying.w...
4849          S.this will increase the chance of winning.
5170    I'm in school now n i'll be in da lab doing so...
                              ...                        
4258    important information 4 orange user . today is...
2310    I have 2 sleeping bags, 1 blanket and paper an...
3631    Get the official ENGLAND poly ringtone or colo...
873                       I'll text you when I drop x off
493                      Sorry,in meeting I'll call later
Name: Message, Length: 1393, dtype: object

In [12]:
x_train[:4]

1964    Yes :)it completely in out of form:)clark also...
4794    Or u ask they all if next sat can a not. If al...
2734                            Do ü noe if ben is going?
4404                               Just getting back home
Name: Message, dtype: object

In [13]:
y_train[:4]

1964    0
4794    0
2734    0
4404    0
Name: spam, dtype: int64

#### Create bag of words representation using **CountVectorization**

In [14]:
v = CountVectorizer()
x_train_cv = v.fit_transform(x_train.values)
x_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [46]:
x_train_cv.toarray().shape

(4179, 7465)

In [16]:
display(v.get_feature_names_out())

array(['00', '000', '000pes', ..., 'zyada', 'èn', 'ú1'], dtype=object)

In [17]:
v.get_feature_names_out()[1000]

'arcade'

In [18]:
v.vocabulary_

{'yes': 7412,
 'it': 3606,
 'completely': 1857,
 'in': 3492,
 'out': 4802,
 'of': 4698,
 'form': 2842,
 'clark': 1753,
 'also': 885,
 'utter': 6960,
 'waste': 7121,
 'or': 4767,
 'ask': 1046,
 'they': 6583,
 'all': 874,
 'if': 3453,
 'next': 4577,
 'sat': 5685,
 'can': 1566,
 'not': 4640,
 'them': 6568,
 'make': 4153,
 'then': 6572,
 'ok': 4718,
 'lor': 4035,
 'do': 2278,
 'noe': 4611,
 'ben': 1255,
 'is': 3594,
 'going': 3047,
 'just': 3716,
 'getting': 3005,
 'back': 1144,
 'home': 3334,
 'tmr': 6667,
 'brin': 1445,
 'lar': 3849,
 'aiya': 850,
 'later': 3862,
 'come': 1832,
 'mayb': 4225,
 'neva': 4563,
 'set': 5805,
 'properly': 5245,
 'got': 3073,
 'da': 2054,
 'help': 3264,
 'sheet': 5842,
 'wif': 7234,
 'me': 4232,
 'fine': 2743,
 'absolutly': 728,
 'sexy': 5817,
 'singles': 5943,
 'are': 1003,
 'waiting': 7083,
 'for': 2826,
 'you': 7427,
 'text': 6532,
 'your': 7431,
 'age': 824,
 'followed': 2808,
 'by': 1528,
 'gender': 2982,
 'as': 1038,
 'wither': 7272,
 '23f': 344,
 'gay':

In [19]:
x_train_np = x_train_cv.toarray()
x_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
np.where(x_train_np[0]!=0)

(array([ 885, 1753, 1857, 2842, 3492, 3606, 4698, 4802, 6960, 7121, 7412]),)

In [41]:
# Swap keys and values using dictionary comprehension
swapped_dict = {value: key for key, value in v.vocabulary_.items()}

print(swapped_dict)

{7412: 'yes', 3606: 'it', 1857: 'completely', 3492: 'in', 4802: 'out', 4698: 'of', 2842: 'form', 1753: 'clark', 885: 'also', 6960: 'utter', 7121: 'waste', 4767: 'or', 1046: 'ask', 6583: 'they', 874: 'all', 3453: 'if', 4577: 'next', 5685: 'sat', 1566: 'can', 4640: 'not', 6568: 'them', 4153: 'make', 6572: 'then', 4718: 'ok', 4035: 'lor', 2278: 'do', 4611: 'noe', 1255: 'ben', 3594: 'is', 3047: 'going', 3716: 'just', 3005: 'getting', 1144: 'back', 3334: 'home', 6667: 'tmr', 1445: 'brin', 3849: 'lar', 850: 'aiya', 3862: 'later', 1832: 'come', 4225: 'mayb', 4563: 'neva', 5805: 'set', 5245: 'properly', 3073: 'got', 2054: 'da', 3264: 'help', 5842: 'sheet', 7234: 'wif', 4232: 'me', 2743: 'fine', 728: 'absolutly', 5817: 'sexy', 5943: 'singles', 1003: 'are', 7083: 'waiting', 2826: 'for', 7427: 'you', 6532: 'text', 7431: 'your', 824: 'age', 2808: 'followed', 1528: 'by', 2982: 'gender', 1038: 'as', 7272: 'wither', 344: '23f', 2969: 'gay', 4267: 'men', 345: '23g', 6088: 'sorry', 4043: 'lot', 2885: '

In [45]:
for i in np.where(x_train_np[0]!=0)[0]:
  print(swapped_dict[i])

also
clark
completely
form
in
it
of
out
utter
waste
yes


In [37]:
x_train.iloc[0]

'Yes :)it completely in out of form:)clark also utter waste.'

In [38]:
v.get_feature_names_out()[885]

'also'

#### **Naive Bayes Classifier**

In [22]:
# from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train_cv, y_train)

MultinomialNB()

In [23]:
x_test_cv = v.transform(x_test.values)
y_pred = model.predict(x_test_cv)

In [24]:
print (classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1204
           1       0.96      0.91      0.93       189

    accuracy                           0.98      1393
   macro avg       0.97      0.95      0.96      1393
weighted avg       0.98      0.98      0.98      1393



#### **Test on random data points**

In [25]:
message = {"Spook-tacular savings alert – $800 OFF + up to $100 Alaska bonus"}
message_cv = v.transform(message)
model.predict(message_cv)

array([1])

In [26]:
message = {"Find Your Crew at Crunch!"}
message_cv = v.transform(message)
model.predict(message_cv)

array([0])