<a href="https://colab.research.google.com/github/iJianHuang/GenAI/blob/main/NumPy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# To install the library

# pip install numpy

import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
type(a)

numpy.ndarray

In [4]:
a = np.array([1,2,3], dtype = float)
# a = np.array([1,2,3], dtype = str)
print(a)

[1. 2. 3.]


In [5]:
a.shape

(3,)

In [11]:
a.ndim

1

In [6]:
len(a)

3

In [7]:
b = np.array(
    [
        [1,2,3],
         [4,5,6]
    ])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
type(b)

numpy.ndarray

In [9]:
b.shape

(2, 3)

In [10]:
len(b)

2

In [12]:
b.ndim

2

In [18]:
c = np.array(
    [
      [
          [1,2,3],
          [11,22,33]
       ],
       [
           [4,5,6],
           [44,55,66]
        ],
        [
            [7,8,9],
            [77,88,99]
        ]
    ])
print(c)

[[[ 1  2  3]
  [11 22 33]]

 [[ 4  5  6]
  [44 55 66]]

 [[ 7  8  9]
  [77 88 99]]]


In [16]:
c.ndim

3

In [19]:
c.shape

(3, 2, 3)

In [20]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
a[1, 5]

np.int64(13)

In [24]:
a[0,]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
a[:, 2]

array([ 3, 10])

In [30]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.full((3,3), 50, dtype='int32')

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]], dtype=int32)

In [33]:
np.random.rand(4,4)

array([[0.52411753, 0.5316087 , 0.25343238, 0.36019294],
       [0.48397553, 0.11011956, 0.17423645, 0.70752061],
       [0.38628148, 0.87858242, 0.3186867 , 0.02888774],
       [0.64477117, 0.10507872, 0.47030138, 0.62729289]])

In [35]:
np.random.randint(-4,4, size=(5,5))

array([[-3, -2,  3, -1,  2],
       [-2, -4,  0, -4,  2],
       [ 0, -4,  2,  2, -1],
       [ 0,  2,  2, -1, -3],
       [-1, -1,  1,  1,  1]])

In [39]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

In [51]:
a[:3, -5:]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

In [56]:
zeros = np.zeros((5,5), dtype='int32')
zeros


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [58]:
type(zeros.shape)

tuple

In [63]:
zeros[5//2] = 1
zeros[:, 5//2] = 1
zeros

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int32)

In [64]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [65]:
b = a + 2
b

array([3, 4, 5, 6])

In [68]:
a.min()
np.min(a)

np.int64(1)

In [69]:
a = np.array(
    [
        [1,2,3,4],
         [5,6,7,8]
    ])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
a.sum(axis=0)

array([ 6,  8, 10, 12])

In [71]:
a.sum(axis=1)

array([10, 26])

In [75]:
c = np.array(
    [
      [
          [1,2,3],
          [11,22,33]
       ],
       [
           [4,5,6],
           [44,55,66]
        ],
        [
            [7,8,9],
            [77,88,99]
        ]
    ])
c

array([[[ 1,  2,  3],
        [11, 22, 33]],

       [[ 4,  5,  6],
        [44, 55, 66]],

       [[ 7,  8,  9],
        [77, 88, 99]]])

In [76]:
c.max()

np.int64(99)

In [79]:
c.max(axis=2)

array([[ 3, 33],
       [ 6, 66],
       [ 9, 99]])